#include "mesh/vert/model-base.glsl"
#include "mesh/vert/model-group-transform.glsl"
#include "mesh/vert/model-position.glsl"
#include "mesh/vert/model-diff.glsl"
#include "mesh/vert/model-lum-tex.glsl"
#include "mesh/vert/model-spec.glsl"